repository: https://github.com/mfazrinizar/flutter_secure_dotenv_generator
name: flutter_secure_dotenv_generator
description: A development dependency to generate secure dotenv file for flutter_secure_dotenv package.

version: 1.0.5

environment:
  sdk: ^3.7.0

dependencies:
  analyzer: ^8.1.1
  collection: ^1.19.1
  dotenv: ^4.2.0
  flutter_secure_dotenv: ^1.0.1
  logging: ^1.3.0
  pointycastle: ^3.9.1
  source_gen: ^4.0.2
  source_helper: ^1.3.8

dev_dependencies:
  build_runner: ^2.10.1
  lints: ^6.0.0
  test: ^1.26.3
