repository: https://github.com/mfazrinizar/flutter_secure_dotenv_generator
name: flutter_secure_dotenv_generator
description: A development dependency to generate secure dotenv file for flutter_secure_dotenv package.

version: 1.0.2

environment:
  sdk: ^3.6.0

dependencies:
  analyzer: ^7.2.0
  build: ^2.4.2
  collection: ^1.19.1
  dotenv: ^4.2.0
  flutter_secure_dotenv: ^1.0.1
  logging: ^1.3.0
  pointycastle: ^3.9.1
  source_gen: ^2.0.0
  source_helper: ^1.3.5

dev_dependencies:
  build_runner: ^2.4.14
  lints: ^5.0.0
  test: ^1.24.0
