repository: https://github.com/mfazrinizar/flutter_secure_dotenv_generator
name: flutter_secure_dotenv_generator
description: A development dependency to generate secure dotenv file for flutter_secure_dotenv package.

version: 2.0.0

environment:
  sdk: ^3.8.0

dependencies:
  analyzer: ">=8.0.0 <11.0.0"
  build: ">=3.0.0 <5.0.0"
  collection: ^1.19.1
  dotenv: ^4.2.0
  flutter_secure_dotenv: ^2.0.0
  logging: ^1.3.0
  pointycastle: ^4.0.0
  source_gen: ^4.2.0
  source_helper: ">=1.3.4 <1.3.9"

dev_dependencies:
  build_runner: ^2.11.1
  lints: ^6.1.0
  test: ^1.29.0
